version: '3.8'

services:
  # 前端开发服务
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder
    container_name: blog-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    networks:
      - blog-dev-network
    command: npm run client:dev

  # 后端开发服务
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: builder
    container_name: blog-backend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_PATH=/app/data/blog.db
    env_file:
      - .env.example
    networks:
      - blog-dev-network
    command: npm run server:dev

  # 数据库管理工具
  adminer:
    image: adminer:latest
    container_name: blog-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - blog-dev-network
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite

  # Redis缓存（开发环境可选）
  redis-dev:
    image: redis:alpine
    container_name: blog-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - blog-dev-network
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data

volumes:
  redis-dev-data:
    driver: local

networks:
  blog-dev-network:
    driver: bridge