# Loki Configuration for Blog System
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  log_format: json
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s
  grpc_server_max_recv_msg_size: 104857600  # 100MB
  grpc_server_max_send_msg_size: 104857600  # 100MB

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true
    replay_memory_ceiling: 1GB

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
    build_per_tenant_index: false
    index_gateway_client:
      server_address: ""
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_cancel_period: 24h

limits_config:
  # Ingestion limits
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_line_size: 256KB
  max_line_size_truncate: false
  
  # Query limits
  max_query_length: 721h  # 30 days
  max_query_parallelism: 32
  max_query_series: 10000
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000
  
  # Chunk limits
  max_chunks_per_query: 2000000
  max_concurrent_tail_requests: 10
  
  # Label limits
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
  
  # Retention
  retention_period: 744h  # 31 days
  
  # Rate limiting
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  
  # Reject old samples
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  
  # Creation grace period
  creation_grace_period: 10m
  
  # Enforce metric name
  enforce_metric_name: false
  
  # Split queries by interval
  split_queries_by_interval: 15m
  
  # Query timeout
  query_timeout: 1m
  
  # Max entries limit per query
  max_entries_limit_per_query: 5000
  
  # Max cache freshness
  max_cache_freshness_per_query: 10m
  
  # Cardinality limit
  cardinality_limit: 100000
  max_streams_matchers_per_query: 1000

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_items: 1024
      validity: 24h
  write_dedupe_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_items: 1024
      validity: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 744h  # 31 days
  creation_grace_period: 3h
  poll_interval: 2m
  index_tables_provisioning:
    enable_ondemand_throughput_mode: false
    enable_inactive_throughput_on_demand_mode: false
    provisioned_write_throughput: 1
    provisioned_read_throughput: 300
    inactive_write_throughput: 1
    inactive_read_throughput: 300
  chunk_tables_provisioning:
    enable_ondemand_throughput_mode: false
    enable_inactive_throughput_on_demand_mode: false
    provisioned_write_throughput: 1
    provisioned_read_throughput: 300
    inactive_write_throughput: 1
    inactive_read_throughput: 300

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h
  compression: gzip

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://127.0.0.1:3100
  compress_responses: true
  max_outstanding_per_tenant: 256
  querier_parallelism: 16

query_scheduler:
  max_outstanding_requests_per_tenant: 256
  grpc_client_config:
    max_recv_msg_size: 104857600  # 100MB
    max_send_msg_size: 104857600  # 100MB

querier:
  query_ingesters_within: 3h
  query_timeout: 1m
  tail_max_duration: 1h
  extra_query_delay: 0s
  max_concurrent: 16
  engine:
    timeout: 3m
    max_look_back_period: 30s

ingester_client:
  pool_config:
    health_check_ingesters: true
    client_cleanup_period: 15s
  remote_timeout: 1s
  grpc_client_config:
    max_recv_msg_size: 67108864  # 64MB
    max_send_msg_size: 67108864  # 64MB
    grpc_compression: gzip

distributor:
  ring:
    kvstore:
      store: inmemory

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  external_url: http://loki:3100
  evaluation_interval: 15s
  poll_interval: 1m
  
# Analytics and metrics
analytics:
  reporting_enabled: false

tracing:
  enabled: false

# Common configuration
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Memberlist configuration
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members: []
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
  node_name: ""
  packet_dial_timeout: 5s
  packet_write_timeout: 5s
  pull_push_interval: 30s
  push_pull_interval: 30s
  randomize_node_name: true
  rejoin_interval: 0s
  retransmit_factor: 4
  stream_timeout: 10s
  gossip_interval: 200ms
  gossip_nodes: 3
  gossip_to_dead_nodes_time: 30s
  dead_node_reclaim_time: 0s
  compression_enabled: true
  advertise_addr: ""
  advertise_port: 7946

# Runtime configuration
runtime_config:
  file: /loki/runtime-config.yaml
  period: 10s

# Operational configuration
operational:
  log_level: info
  log_format: json

# Metrics configuration
metrics:
  global:
    evaluation_interval: 15s
  wal_dir: /loki/wal
  remote_write:
    - url: http://prometheus:9090/api/v1/write
      queue_config:
        capacity: 10000
        max_shards: 200
        min_shards: 1
        max_samples_per_send: 1000
        batch_send_deadline: 5s
        min_backoff: 30ms
        max_backoff: 100ms

# Log configuration for different services
log_config:
  level: info
  format: json
  
# Tenant configuration
tenant_config:
  mode: single-tenant

# Cache configuration
cache_config:
  enable_fifocache: true
  fifocache:
    max_size_items: 1024
    validity: 24h

# Bloom configuration (experimental)
bloom_build:
  enabled: false
  builder:
    planner_address: ""
  compactor:
    enabled: false

bloom_gateway:
  enabled: false
  client:
    addresses: []

# Pattern ingester (experimental)
pattern_ingester:
  enabled: false

# Index gateway
index_gateway:
  mode: simple

# Structured metadata
structured_metadata:
  enabled: true
  max_size_kb: 64

# Use boltdb-shipper for index
index_gateway:
  mode: simple

# Limits per tenant (if multi-tenant mode is enabled)
overrides:
  "fake":
    ingestion_rate_mb: 32
    ingestion_burst_size_mb: 64
    max_streams_per_user: 20000
    max_global_streams_per_user: 100000
    retention_period: 2160h  # 90 days

# Feature flags
feature_flags:
  enable_new_distributor: false
  enable_new_ingester: false
  enable_new_querier: false