# Jaeger Configuration for Blog System
# This configuration sets up Jaeger for distributed tracing

# Collector configuration
collector:
  # OTLP receiver configuration
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
  
  # Jaeger receiver configuration
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832
  
  # Zipkin receiver configuration
  zipkin:
    endpoint: 0.0.0.0:9411
  
  # Health check configuration
  health_check:
    endpoint: 0.0.0.0:13133
  
  # Metrics configuration
  metrics:
    address: 0.0.0.0:14269
    namespace: jaeger
  
  # Log level
  log_level: info

# Query service configuration
query:
  # Base path for UI
  base_path: /
  
  # Static files path
  static_files: /go/jaeger-ui/
  
  # UI configuration
  ui_config: /etc/jaeger/ui-config.json
  
  # Health check
  health_check_http_port: 16687
  
  # Metrics
  metrics_http_port: 16686
  
  # GRPC server
  grpc_server_host_port: 0.0.0.0:16685
  
  # HTTP server
  http_server_host_port: 0.0.0.0:16686
  
  # Log level
  log_level: info
  
  # Query timeout
  query_timeout: 30s
  
  # Max clock skew adjustment
  max_clock_skew_adjustment: 0s

# Agent configuration
agent:
  # Jaeger thrift compact
  jaeger_thrift_compact_port: 6831
  
  # Jaeger thrift binary
  jaeger_thrift_binary_port: 6832
  
  # Jaeger thrift HTTP
  jaeger_thrift_http_port: 14268
  
  # Zipkin thrift compact
  zipkin_thrift_compact_port: 5775
  
  # Config server URL
  config_server_url: http://jaeger-collector:14269
  
  # Metrics
  metrics_http_port: 14271
  
  # Health check
  health_check_http_port: 14270
  
  # Log level
  log_level: info

# Storage configuration
storage:
  type: elasticsearch
  
  elasticsearch:
    # Server URLs
    server_urls:
      - http://elasticsearch:9200
    
    # Index configuration
    index_prefix: jaeger
    
    # Shards and replicas
    num_shards: 1
    num_replicas: 0
    
    # Bulk configuration
    bulk:
      actions: 1000
      size: 5MB
      workers: 1
      flush_interval: 200ms
    
    # Timeout
    timeout: 0s
    
    # Username and password (if needed)
    # username: elastic
    # password: changeme
    
    # TLS configuration
    tls:
      enabled: false
      # ca: /path/to/ca.crt
      # cert: /path/to/client.crt
      # key: /path/to/client.key
      # server_name: elasticsearch
      skip_host_verify: false
    
    # Index settings
    create_index_templates: true
    
    # Adaptive sampling
    adaptive_sampling:
      sampling_store_type: elasticsearch
    
    # Archive storage
    archive:
      enabled: true
      index_prefix: jaeger-archive
      max_span_age: 72h
    
    # Rollover
    rollover:
      conditions:
        max_age: 24h
        max_size: 1GB
    
    # ILM (Index Lifecycle Management)
    ilm:
      enabled: true
      policy_name: jaeger-ilm-policy
    
    # Mapping configuration
    mapping:
      cache_size: 75
      
# Sampling configuration
sampling:
  # Default sampling strategy
  default_strategy:
    type: probabilistic
    param: 0.1  # 10% sampling rate
  
  # Per-service sampling strategies
  per_service_strategies:
    - service: blog-frontend
      type: probabilistic
      param: 0.2  # 20% sampling for frontend
      max_traces_per_second: 100
    
    - service: blog-backend
      type: probabilistic
      param: 0.3  # 30% sampling for backend
      max_traces_per_second: 200
    
    - service: blog-api
      type: probabilistic
      param: 0.5  # 50% sampling for API
      max_traces_per_second: 150
    
    - service: postgres
      type: probabilistic
      param: 0.1  # 10% sampling for database
      max_traces_per_second: 50
    
    - service: redis
      type: probabilistic
      param: 0.05  # 5% sampling for cache
      max_traces_per_second: 30
  
  # Operation sampling strategies
  per_operation_strategies:
    - service: blog-backend
      operation: GET /api/health
      type: probabilistic
      param: 0.01  # 1% sampling for health checks
    
    - service: blog-backend
      operation: POST /api/auth/login
      type: probabilistic
      param: 1.0  # 100% sampling for login
    
    - service: blog-backend
      operation: POST /api/posts
      type: probabilistic
      param: 1.0  # 100% sampling for post creation
    
    - service: blog-backend
      operation: GET /api/posts
      type: probabilistic
      param: 0.1  # 10% sampling for post listing
  
  # Adaptive sampling
  adaptive_sampling:
    enabled: true
    max_traces_per_second: 500
    strategies_refresh_interval: 60s

# Metrics configuration
metrics:
  # Prometheus metrics
  prometheus:
    enabled: true
    namespace: jaeger
    
  # Additional metrics
  factory: prometheus
  
  # HTTP metrics server
  http_route: /metrics

# Logging configuration
logging:
  level: info
  format: json
  
  # Log sampling
  sampling:
    initial: 100
    thereafter: 100

# Health check configuration
health_check:
  enabled: true
  http_port: 14269

# Admin configuration
admin:
  http:
    host_port: 0.0.0.0:14269

# Processor configuration
processors:
  # Batch processor
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  # Memory limiter
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s
  
  # Resource processor
  resource:
    attributes:
      - key: service.namespace
        value: blog-system
        action: upsert
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.version
        from_attribute: version
        action: upsert
  
  # Span processor
  span:
    name:
      # Rename operations
      to_attributes:
        rules:
          - pattern: ^GET /api/posts/([0-9]+)$
            name: GET /api/posts/{id}
          - pattern: ^GET /api/users/([0-9]+)$
            name: GET /api/users/{id}
          - pattern: ^PUT /api/posts/([0-9]+)$
            name: PUT /api/posts/{id}
          - pattern: ^DELETE /api/posts/([0-9]+)$
            name: DELETE /api/posts/{id}

# Extensions configuration
extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
  
  # pprof extension
  pprof:
    endpoint: 0.0.0.0:1777
  
  # zpages extension
  zpages:
    endpoint: 0.0.0.0:55679

# Service configuration
service:
  # Extensions
  extensions:
    - health_check
    - pprof
    - zpages
  
  # Pipelines
  pipelines:
    # Traces pipeline
    traces:
      receivers:
        - otlp
        - jaeger
        - zipkin
      processors:
        - memory_limiter
        - resource
        - span
        - batch
      exporters:
        - elasticsearch
    
    # Metrics pipeline
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - batch
      exporters:
        - prometheus
    
    # Logs pipeline (if needed)
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - batch
      exporters:
        - elasticsearch

# Exporters configuration
exporters:
  # Elasticsearch exporter
  elasticsearch:
    endpoints:
      - http://elasticsearch:9200
    index: jaeger-traces
    mapping:
      mode: ecs
    
  # Prometheus exporter
  prometheus:
    endpoint: 0.0.0.0:14269
    namespace: jaeger
    const_labels:
      service: jaeger
      environment: production

# Feature flags
feature_flags:
  # Enable adaptive sampling
  adaptive_sampling: true
  
  # Enable archive storage
  archive_storage: true
  
  # Enable query guardrails
  query_guardrails: true
  
  # Enable UI configuration
  ui_config: true

# UI configuration
ui:
  # Dependencies
  dependencies:
    menu_enabled: true
  
  # Archive traces
  archive_traces:
    enabled: true
  
  # Tracking
  tracking:
    ga_id: ""  # Google Analytics ID if needed
  
  # Deep dependencies
  deep_dependencies:
    menu_enabled: true
  
  # Monitor
  monitor:
    menu_enabled: true
    
  # Search
  search:
    max_lookback: 168h  # 7 days
    max_duration: 24h
    default_limit: 20
  
  # Critical path
  critical_path:
    enabled: true

# Security configuration
security:
  # CORS
  cors:
    allowed_origins:
      - "*"
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      - "X-Requested-With"
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
  
  # Authentication (if needed)
  # auth:
  #   type: oauth2
  #   oauth2:
  #     client_id: your-client-id
  #     client_secret: your-client-secret
  #     auth_url: https://your-auth-provider.com/auth
  #     token_url: https://your-auth-provider.com/token
  #     redirect_url: http://jaeger:16686/oauth/callback

# Performance tuning
performance:
  # Memory settings
  memory:
    max_memory_usage: 1GB
    gc_target_percentage: 75
  
  # Connection settings
  connections:
    max_idle_conns: 100
    max_open_conns: 200
    conn_max_lifetime: 1h
  
  # Timeouts
  timeouts:
    read_timeout: 30s
    write_timeout: 30s
    idle_timeout: 60s