# Blog System Alert Rules for Prometheus
groups:
  # System Level Alerts
  - name: system.rules
    interval: 30s
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
          component: cpu
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-cpu"
          dashboard_url: "http://grafana:3000/d/system/system-overview?var-instance={{ $labels.instance }}"

      # Critical CPU Usage
      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
          service: system
          component: cpu
        annotations:
          summary: "Critical CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/critical-cpu"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
          component: memory
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 85% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-memory"

      # Critical Memory Usage
      - alert: CriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
          component: memory
        annotations:
          summary: "Critical memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 95% for more than 2 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/critical-memory"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
          component: disk
        annotations:
          summary: "High disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is above 85% on {{ $labels.mountpoint }}. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-disk"

      # Critical Disk Usage
      - alert: CriticalDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 95
        for: 2m
        labels:
          severity: critical
          service: system
          component: disk
        annotations:
          summary: "Critical disk usage detected on {{ $labels.instance }}"
          description: "Disk usage is above 95% on {{ $labels.mountpoint }}. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/critical-disk"

      # Instance Down
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          service: system
          component: availability
        annotations:
          summary: "Instance {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/instance-down"

  # Application Level Alerts
  - name: application.rules
    interval: 30s
    rules:
      # Blog Frontend Down
      - alert: BlogFrontendDown
        expr: up{job="blog-frontend"} == 0
        for: 1m
        labels:
          severity: critical
          service: blog-frontend
          component: web
        annotations:
          summary: "Blog Frontend is down"
          description: "Blog Frontend service has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/frontend-down"

      # Blog Backend Down
      - alert: BlogBackendDown
        expr: up{job="blog-backend"} == 0
        for: 1m
        labels:
          severity: critical
          service: blog-backend
          component: api
        annotations:
          summary: "Blog Backend API is down"
          description: "Blog Backend API service has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/backend-down"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="blog-backend"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: blog-backend
          component: performance
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds for more than 5 minutes. Current value: {{ $value }}s"
          runbook_url: "https://runbooks.example.com/high-response-time"

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5..",job="blog-backend"}[5m]) / rate(http_requests_total{job="blog-backend"}[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: blog-backend
          component: reliability
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-error-rate"

      # Critical Error Rate
      - alert: CriticalErrorRate
        expr: rate(http_requests_total{status=~"5..",job="blog-backend"}[5m]) / rate(http_requests_total{job="blog-backend"}[5m]) * 100 > 20
        for: 2m
        labels:
          severity: critical
          service: blog-backend
          component: reliability
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is above 20% for more than 2 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/critical-error-rate"

      # Low Request Rate (Possible DDoS or Service Issue)
      - alert: LowRequestRate
        expr: rate(http_requests_total{job="blog-backend"}[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
          service: blog-backend
          component: traffic
        annotations:
          summary: "Unusually low request rate detected"
          description: "Request rate is below 0.1 requests/second for more than 10 minutes. Current value: {{ $value }}"
          runbook_url: "https://runbooks.example.com/low-request-rate"

      # High Request Rate (Possible DDoS)
      - alert: HighRequestRate
        expr: rate(http_requests_total{job="blog-backend"}[5m]) > 100
        for: 2m
        labels:
          severity: warning
          service: blog-backend
          component: traffic
        annotations:
          summary: "High request rate detected"
          description: "Request rate is above 100 requests/second for more than 2 minutes. Current value: {{ $value }}"
          runbook_url: "https://runbooks.example.com/high-request-rate"

  # Database Alerts
  - name: database.rules
    interval: 30s
    rules:
      # PostgreSQL Down
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          service: postgresql
          component: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/postgres-down"

      # High Database Connections
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: postgresql
          component: connections
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-db-connections"

      # Slow Database Queries
      - alert: SlowDatabaseQueries
        expr: pg_stat_activity_max_tx_duration{datname!=""} > 300
        for: 2m
        labels:
          severity: warning
          service: postgresql
          component: performance
        annotations:
          summary: "Slow database queries detected"
          description: "Long running queries detected in database {{ $labels.datname }}. Duration: {{ $value }}s"
          runbook_url: "https://runbooks.example.com/slow-queries"

      # Database Deadlocks
      - alert: DatabaseDeadlocks
        expr: increase(pg_stat_database_deadlocks[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: postgresql
          component: locks
        annotations:
          summary: "Database deadlocks detected"
          description: "{{ $value }} deadlocks detected in database {{ $labels.datname }} in the last 5 minutes."
          runbook_url: "https://runbooks.example.com/deadlocks"

  # Cache Alerts
  - name: cache.rules
    interval: 30s
    rules:
      # Redis Down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/redis-down"

      # High Redis Memory Usage
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: redis
          component: memory
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is above 90% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/high-redis-memory"

      # Redis Connection Issues
      - alert: RedisConnectionIssues
        expr: redis_rejected_connections_total > 0
        for: 1m
        labels:
          severity: warning
          service: redis
          component: connections
        annotations:
          summary: "Redis connection rejections detected"
          description: "Redis is rejecting connections. Total rejected: {{ $value }}"
          runbook_url: "https://runbooks.example.com/redis-connections"

  # Container Alerts
  - name: container.rules
    interval: 30s
    rules:
      # Container High CPU
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: docker
          component: container
        annotations:
          summary: "Container {{ $labels.name }} high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is above 80% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/container-high-cpu"

      # Container High Memory
      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: docker
          component: container
        annotations:
          summary: "Container {{ $labels.name }} high memory usage"
          description: "Container {{ $labels.name }} memory usage is above 90% for more than 5 minutes. Current value: {{ $value }}%"
          runbook_url: "https://runbooks.example.com/container-high-memory"

      # Container Restart
      - alert: ContainerRestart
        expr: increase(container_start_time_seconds{name!=""}[5m]) > 0
        for: 0m
        labels:
          severity: warning
          service: docker
          component: container
        annotations:
          summary: "Container {{ $labels.name }} restarted"
          description: "Container {{ $labels.name }} has restarted {{ $value }} times in the last 5 minutes."
          runbook_url: "https://runbooks.example.com/container-restart"

  # Load Balancer Alerts
  - name: loadbalancer.rules
    interval: 30s
    rules:
      # Traefik Down
      - alert: TraefikDown
        expr: up{job="traefik"} == 0
        for: 1m
        labels:
          severity: critical
          service: traefik
          component: loadbalancer
        annotations:
          summary: "Traefik load balancer is down"
          description: "Traefik load balancer has been down for more than 1 minute."
          runbook_url: "https://runbooks.example.com/traefik-down"

      # High Traefik Response Time
      - alert: HighTraefikResponseTime
        expr: histogram_quantile(0.95, rate(traefik_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: traefik
          component: performance
        annotations:
          summary: "High Traefik response time"
          description: "Traefik 95th percentile response time is above 1 second for more than 5 minutes. Current value: {{ $value }}s"
          runbook_url: "https://runbooks.example.com/high-traefik-response"

  # Monitoring Stack Alerts
  - name: monitoring.rules
    interval: 60s
    rules:
      # Prometheus Target Down
      - alert: PrometheusTargetDown
        expr: up == 0
        for: 5m
        labels:
          severity: warning
          service: prometheus
          component: monitoring
        annotations:
          summary: "Prometheus target {{ $labels.instance }} is down"
          description: "Prometheus target {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
          runbook_url: "https://runbooks.example.com/prometheus-target-down"

      # Prometheus Configuration Reload Failed
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 5m
        labels:
          severity: warning
          service: prometheus
          component: configuration
        annotations:
          summary: "Prometheus configuration reload failed"
          description: "Prometheus configuration reload has failed for more than 5 minutes."
          runbook_url: "https://runbooks.example.com/prometheus-config-reload"

      # Grafana Down
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 2m
        labels:
          severity: warning
          service: grafana
          component: visualization
        annotations:
          summary: "Grafana is down"
          description: "Grafana has been down for more than 2 minutes."
          runbook_url: "https://runbooks.example.com/grafana-down"

      # Alertmanager Down
      - alert: AlertmanagerDown
        expr: up{job="alertmanager"} == 0
        for: 2m
        labels:
          severity: critical
          service: alertmanager
          component: alerting
        annotations:
          summary: "Alertmanager is down"
          description: "Alertmanager has been down for more than 2 minutes."
          runbook_url: "https://runbooks.example.com/alertmanager-down"

  # Business Logic Alerts
  - name: business.rules
    interval: 60s
    rules:
      # Low User Registration Rate
      - alert: LowUserRegistrationRate
        expr: rate(user_registrations_total[1h]) < 0.01
        for: 2h
        labels:
          severity: info
          service: blog-backend
          component: business
        annotations:
          summary: "Low user registration rate"
          description: "User registration rate is below 0.01 per hour for more than 2 hours. Current rate: {{ $value }}"
          runbook_url: "https://runbooks.example.com/low-registration"

      # High Failed Login Attempts
      - alert: HighFailedLoginAttempts
        expr: rate(failed_login_attempts_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          service: blog-backend
          component: security
        annotations:
          summary: "High failed login attempts detected"
          description: "Failed login attempts rate is above 10 per minute for more than 5 minutes. Current rate: {{ $value }}"
          runbook_url: "https://runbooks.example.com/high-failed-logins"

      # No New Posts Created
      - alert: NoNewPostsCreated
        expr: increase(posts_created_total[24h]) == 0
        for: 24h
        labels:
          severity: info
          service: blog-backend
          component: business
        annotations:
          summary: "No new posts created in 24 hours"
          description: "No new blog posts have been created in the last 24 hours."
          runbook_url: "https://runbooks.example.com/no-new-posts"